---
name: Firefox
version: dev
slug: hafirefox
description: Firefox Browser
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - i386
panel_icon: "mdi:firefox"
map:
  - config:rw
ports:
  5900/tcp: null
ports_description:
  5900/tcp: "Web interface"
